### ISSUE TITLE
[ENTREGA 1° Recuperatorio objetos] Swifties

### ISSUE THREAD

**Issue by aylulavoria** [pdep-lunes-tarde/2024-objetos-recuperatorio-1-aylulavoria#1]
Subo el parcial. Saludos!

**Borren los ids de los tutores que no son de tu grupo así no les llega una notificación a todos:**
Emiliano Salvano y Luca Pavón @EmilianoSalvano @Lpavn
Juan Fernandes y Lucas Zheng @juanFdS @zhl27 
Juani Schuhmann y Dante Ortiz @jschuhmann47 @Effloresc3 
Tomás Antonio @T-J-Antonio
Gustavo Crespi y Manuel Torrente @gcrespi @manutorrente

**Comment by JuanFdS** [comment]
## Parte A

### Punto 1
❌ Los objetos mágicos entienden `poderTotal` con un argumento, no `poder`, por lo tanto esta implementación de `poderTotal` en el mago no funciona. Además, no debería _filtrarse_ la lista de objetos, sino _transformarse_ en puntajes, por lo que sería más correcto usar `map` y luego `sum`, o bien directamente `sum` de aridad 1 con un bloque. El método tampoco retorna nada, sino que realiza un cálculo y no utiliza su resultado.
❌ Las túnicas también tienen poder base y lo aportan al poder total.
❌ Los amuletos no son polimórficos con el resto de objetos, no se puede consultar su poder.
### Punto 2
❌ En esta implementación, al modelarlo usando herencia, el mago siempre va a ser de la misma categoría, lo cual no es correcto según el enunciado:
> Estas características dependen de la categoría que el mago tenga actualmente, la cual puede cambiar a lo largo del tiempo.
❌ ¿Por qué un mago recibe dos magos más por parámetro al desafiar? ¿No debería él desafiar a uno solo?
❌ No hay implementada una conexión entre el hecho de vencer un mago a otro y el hecho de transferir los puntos, cuando lo segundo debería ser consecuencia de lo primero.
## Parte B
### Punto 1
❌ La validación se encuentra en el método `crearGremio` de la clase `Gremio`, por lo que el gremio fue creado _antes de ser validado_ y la validación sólo se realiza al cambiar la lista. Como indica la consigna, esto debería haberse ubicado en el método `initialize` o bien en un objeto auxiliar que se encargue de instanciar gremios. Además, se envían a la variable `listadoDeMagos` mensajes entendidos por números y por listas, eso tampoco es correcto y fallará al ejecutarlo.
### Punto 2
❌ Incompleto.
### Punto 3
❌ Lo implementado en el método `esLider` no coincide con el comentario. En lugar de `filter`, debería haberse usado `max` de aridad 1 para obtener el miembro con máximo poder.
## Tests
N/A.

Aclaración: los nombres de las clases en Wollok efectivamente van con mayúscula. Está bien que el IDE te tire el warning.

-----------------------

Nota: 2
